dxe/adb

model/activist.go
model/db.go

The process of inserting new users and retrieving them is now wrapped in
a database transaction. A unique constraint has been placed on the name
field in the activists table to prevent duplicate names.

Improve error handling when inserting new users into database.

---

frontend/ActivistList.vue
frontend/chosen_utils.js
frontend/event_list.js
main.go
model/activist.go
model/activist_test.go
model/db.go

Add feature to merge one activist into another.
It works by hiding the activist you're merging and assigning all of their attendance to the "merged" user.
- Add /activist/merge
- Add `merged_activist_attendance` table so we can keep track of the merges that have been done so that they can be undone. The undo feature isn't implemented yet, we'll do that once we let people view hidden activists.
Some things I'd like feedback on:
- Is there a better name than "mergedUserID" for the ID that we're merging into?
- We don't have any checks that keep people from using the pre-merged user when taking attendance. Should we check that an activist hasn't been merged when we check attendance?

Add "merge activist"

---

Makefile
scripts/.gitignore
scripts/create_db.go
scripts/create_db_wrapper.sh

When running `make dev_db`, the user is now prompted for their development email, and it is injected into `adb_db.adb_users` as an admin. Alternatively, the user can set the environment variable `DXE_DEV_EMAIL` in e.g. their `.bashrc` and never see the prompt.
I left the existing emails in the database creation script, though I can pull these out if you'd like to make this script a little cleaner =)

Add prompt for the developers email to `make dev_db`

---

model/db.go
scripts/create_db.go

"CREATE TABLE" queries were generated with MySQL's "SHOW CREATE TABLE"
command, and then cleaned up by hand (e.g., removing back quotes,
upper-casing type names, stripping unnecessary field attributes).
Also, simplified the UNIQUE constraints to be compatible with
PostgreSQL, and removed unnecessary index names.
Fixes #30.

Sync "make dev_db" with production schema

---

.babelrc
package.json
webpack.config.js

Two notable changes:
1. webpack now natively support development and production build "modes",
which obviates the need for manually configuring additional minimization
plugins in production mode. So our webpack.config.js file simplifies a bit.
(Exception: vue-loader now requires a webpack plugin.)
2. babel config now automatically detects which modern JavaScript constructs
need to be transpiled to support legacy browsers.
While here, remove unused vue-infinite-loading dependency.
Fixes #33.

Update npm dependencies

---

.babelrc
package.json
webpack.config.js

Two notable changes:
1. webpack now natively support development and production build "modes",
which obviates the need for manually configuring additional minimization
plugins in production mode. So our webpack.config.js file simplifies a bit.
(Exception: vue-loader now requires a webpack plugin.)
2. babel config now automatically detects which modern JavaScript constructs
need to be transpiled to support legacy browsers.
While here, remove unused vue-infinite-loading dependency.
Fixes #33.

Update npm dependencies (retry)

---

frontend/ActivistList.vue
frontend/CirclesList.vue
frontend/EventList.vue
frontend/UserList.vue
static/css/style.css
templates/403.html
templates/header.html
templates/login.html
templates/logout.html

For each removed CSS class name "foo", I couldn't find ".foo" anywhere
in a CSS source file.

remove unused CSS class names

---

config/config.go

Previously we only allowed using environment variables for configuration
during production mode, whereas development mode had hard-coded values.
With this commit, we always allow using environment variables, but for
development mode we fallback to the hard-coded values. Production mode
still requires all values to be explicitly configured.

always allow config using environment variables

---

main.go
model/adb_auth.go
model/circles.go
model/working_groups.go
model/working_groups_test.go

The GetFoosJSON functions don't need to take Options parameters, since
they're not actually allowed to set any options anyway. Also,
eliminate the unused options (e.g., the "Name" field for circles and
working groups) and unimplemented options (e.g., most of the "User"
fields).
Low hanging fruit in trying to simplify the DB model to make better
sense of it.

remove unused model options

---

main.go
templates/connection_new.html
templates/event_new.html

We don't actually incorporate the event details into the page using
the server-side templates anymore, so no point in querying the
database. Instead we can simply pass the event ID directly through.

simplify event_new and connection_new page rendering

---

Dockerfile
README.md
config/config.go
go.mod
go.sum
main.go
model/db.go
model/event.go
scripts/create_db.go
survey_mailer/survey_mailer.go

Currently, we have mysql scripts that run on a regular basis to export event attendance data to csv files. These csv files are publicly accessible and imported into Google Sheets. From there, there are multiple Google Apps Scripts that run to send survey emails via Gmail.
This pull request will add all of the survey-sending functionality directly into the ADB.
Here are the steps I will follow when merging this:
- Disable current GAS scripts on various spreadsheets: meetup, chapter mtg, protest.
- Add survey_sent col to prod events database (and set to 1 for previous day's events to prevent sending duplicates).
- Add new environment variables to docker instance (see readme).
- Remove surveys.sql from mysql-files and delete the csv files from www.

integrate surveys into adb

---

config/config.go
frontend/UserList.vue
go.mod
go.sum
main.go
templates/header.html

The CSRF tokens that are generated can be reused for subsequent requests.
@mdempsky It would be useful to verify that these tokens can't be used across user accounts -- does that need to be tested in prod? E.g., I shouldn't be able to log in as myself, collect the CSRF base token and a request token, and then trick a user into submitting these values and have the server accept the request.
To generate the 32-byte random key for CSRF authentication, you can use `LC_ALL=C tr -dc '[:alnum:]' < /dev/urandom | head -c20`.

[WIP] Add CSRF protection to admin endpoints

---

config/config.go
main.go
model/activist.go
model/db.go
model/discord.go
templates/discord.html

The idea behind this is to verify people's email address when they join the DxE Discord server, so that we can link their Discord ID to their activist record in the ADB.
The Discord bot (a separate node.js app) will message people when they join the server & hit these ADB endpoints to handle the user confirmation flow.

added new API endpoints for discord bot

---

config/config.go

- fix Goland processor ENV variables in PROD by making them not mandatory

fix Goland processor ENV variables in PROD by making them not mandatory

---

adb-forms/processor/config.go
config/config.go
main.go

Add `prod` as a flag for the Go application to fix the "flag provided but not defined: -prod" bug that appeared when adding the `FORM_PROCESSOR_LOG_LEVEL` flag.

fix "prod" flag bug

---

form_processor/functions.go
form_processor/processor.go

- convert double logs into single logs
- use the same wording
- use the same punctuation
- remove duplicate info, e.g. "error"

[Form Processor] standardize logs

---

package-lock.json
package.json

Why: avoid unexpected differences between different environments
What: pin all node packages to their current minimum version

Pin all node packages

---

config/config.go
main.go
members/auth.go

Why: be able to work on more parts of the application while offline
What: do not exit on OIDC provider construction failures. Log a warning instead.

Do not exit on OIDC provider construction failures

---

.gitignore
Dockerfile
form_processor/README.md
form_processor/config.go
form_processor/processor.go

Why: there is no need to have a lock file anymore since the application is Dockerized so there won't be multiple processes competing for the same lock file
What: remove anything that was based on the concept of having a lock file from the codebase

Remove file lock concept from form processor

---

form_processor/functions.go

Why: these names were based on an old region that was specific to "applications" but now this procedure deals with both "applications" and "interests".
What: rename variables in `getResponsesToProcess` to generic names.

rename variables in `getResponsesToProcess` to generic names

---

model/activist.go
model/geo_helpers.go
package-lock.json

Attempt at geocoding addresses with google API on activist update
Tested locally on a variety of addresses. Google Geocoding API has a bit undefined behavior when entering bogus addresses but seems to work well with real addresses. 
Not sure if I should include package-lock.json changes in my commits?

Geocoding on activist update

---

frontend/FormInternational.vue
frontend/external/vue-google-autocomplete/src/VueGoogleAutocomplete.vue
frontend/static/css/style.css

Previously, the City field autocomplete dropdown would be positioned correctly only if the user did not scroll from the top of the page, a known issue with vue-google-autocomplete:
https://github.com/MadimetjaShika/vuetify-google-autocomplete/issues/100
On small screens, if the "City" field was "below the fold", the dropdown would be hidden entirely.
The issue is fixed by removing "overflow: auto" on html/body, which was added here:
https://github.com/dxe/adb/commit/ae799dcf1795c20fed7a3dd3aefd60bfc9db5542#diff-a5ea33c888430601a659bcbef2da1944097953737f2606282efc13ca6e5fbabaR2
After removing overflow: auto, white margins appeared above and below the background image. Removing the duplicate body CSS rule fixed this. Removing "height: 100%" fixed something else that started happening too. …

Fix misplaced City dropdown on dxe.io/join

---

.vscode/launch.json

Wasn't showing build status; made it hard to know when to refresh the page to see recent changes.

Fix "webpack watch" in debugger config

---

frontend/ChapterList.vue
server/src/model/chapters.go

Add social fields for international organizers

---

server/templates/event_list.html

It was showing the navigation as if the user was always an admin. Introduced here, probably for testing: https://github.com/dxe/adb/commit/f02c797c0224d0076e84ebc2ebe6a4d68c2ef104#diff-cb8123a015cec42248e9e3799392ad0185efe8c5b725d024ca068afa333181c5L4

Undo navigation bug on event list page

---

server/src/model/activist.go

When an activist is updated in ADB, subscribe them to the mailing list near their home chapter (chapter near their zip code) rather than to this chapter's mailing list. Also add them to the home chapter ADB if different.
This is done by telling the sign-up service that the current chapter is the "source chapter", freeing up "target chapter" to be selected automatically based on zip code.

fix: add activists only to mailing list near zip

---

server/src/form_processor/application_form_processor.go
server/src/form_processor/interest_form_processor.go

I'm seeing alerts in prod due to processing errors, but the database shows they are still getting marked as processed.
Maybe unit tests don't fail due to a difference in Maria DB used in prod vs MySql or lack of coverage, but anyway hopefully this fixes it.

fix: Do not fail when rows affected > 1 in application processors

---

server/scripts/db-migrations/20250810034041_activist_timestamps.down.sql
server/scripts/db-migrations/20250810034041_activist_timestamps.up.sql
server/src/form_processor/application_form_processor.go
server/src/form_processor/interest_form_processor.go
server/src/form_processor/interest_form_processor_test.go
server/src/main.go
server/src/model/activist.go
server/src/model/activist_test.go
server/src/model/activist_test_utils.go

* feat: add timestamp columns to activists
This allows smarter merging of activist records. This is especially
important because in the future we may decide to merge activist records
across chapters. We suspect there may be a lot of activists in multiple
chapters now that check-in forms systematically duplicate activists
across chapters when someone gives a zip code near one chapter (which is
presumed to be their home chapter) on a check-in form belonging to
another chapter (which needs the same activist info for attendance).
* chore: deduplicate update queries for activist update
One was missing dev_application_date and dev_application_type and the
other was missing lat, lng and coords_updated. Combining so all fields
will get updated in all cases.

feat: add timestamp columns to activists

---

server/scripts/create_db_wrapper/create_db.go
server/src/event_sync/event_sync.go
server/src/main.go
server/src/model/activist.go
server/src/model/activist_test.go
server/src/model/adb_auth.go
server/src/model/chapters.go
server/src/model/event_test.go
server/src/model/forms.go
server/src/model/geo_helpers.go
server/src/model/working_groups_test.go

* refactor: use constants for SF Bay ids
* test: use real database and cookies for dev test user
This removes a noisy message about not getting the chapter ID from the
cookie when there was no cookie.
* chore: replace fmt.Print* with log.Print* statements

Auth and logging fixes

---

server/src/config/config.go
server/src/form_processor/processor.go

The form processor was causing race conditions with itself, when two instances would go to insert the same activist. This was causing noisy alerts in AWS.

fix: avoid overlapping form processor runs

---

server/scripts/create_db_wrapper/create_db.go
server/src/main.go
server/src/model/activist.go
server/src/model/activist_test.go

Fixes https://app.asana.com/1/71341131816665/project/1204966015842755/task/1211451554791982
A previous simplification of logic to update activists resulted in dev_application_date and dev_application_type fields getting cleared whenever the activist as updated in ADB by a user. These fields were reintroduced to the update query where they were previously excluded, but their values were not set in the CleanActivistData function called from the save handler. This commit adds those fields to the CleanActivistData save handler for completeness, but also removes these fields from the SQL query once again as they should not be editable by the user.

fix: do not forget dev-application-* fields on update

---

frontend/ActivistList.vue
server/src/main.go
server/src/model/activist.go

The SQL query behind it was outdated (did not match the list generated in the UI) and it seems no one uses it.

chore: remove community prospects csv export
