dxe/adb

- frontend/ActivistList.vue
Also, disable the save button when it's first clicked so that the user doesn't click it twice.
> Automatically close modal on save

- frontend/UserList.vue
- frontend/user_list.js
- main.go
- model/adb_auth.go
- templates/403.html
- templates/header.html
- templates/user_list.html
- webpack.config.js
Adds an Admin feature for managing ADB Users.
~~This is still a WIP, but has most of the functionality.~~ Modeled
implementation after Activists feature.
Currently lists Users, and allows adding/updating a User,
TODO:
Allow Deleting a User
Update Admin & Disabled from quick menu button (like Hide & Merge for
Activists)
Fix spacing
> feat(admin): User management

- frontend/ActivistList.vue
- frontend/UserList.vue
- frontend/WorkingGroupList.vue
- frontend/directives/focus.js
- frontend/external/search-select/BasicSelect.vue
- frontend/external/search-select/README.md
- frontend/external/search-select/common.css
- frontend/external/search-select/common.js
- frontend/external/search-select/commonMixin.js
- frontend/working_group_list.js
- main.go
- model/db.go
- model/working_groups.go
- model/working_groups_test.go
- package.json
- static/css/style.css
- templates/header.html
- templates/working_group_list.html
- webpack.config.js
Adds the working group page.
- Adds tables `working_groups` and `working_group_members`.
- Vendors a fork of https://github.com/moreta/vue-search-select, modified to be similar to chosen-js.
Will follow up with a pull request that adds mailing list syncing.
> Add working groups page

- .babelrc
- package.json
- webpack.config.js
Reverts dxe/adb#34
Getting this error when trying to deploy:
Error: Cannot find module 'vue-loader/lib/plugin'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/media/sf_go/src/github.com/dxe/adb/webpack.config.js:3:23)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
npm ERR! Linux 4.4.0-119-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 build: `NODE_ENV=production webpack …
> Revert "Update npm dependencies"

- frontend/UserList.vue
- main.go
- model/adb_auth.go
- model/db.go
- scripts/create_db.go
- scripts/db-migrations/add-users-roles.sql
- templates/header.html
Implements a User Role based authentication management, and Admin UI to assign roles.
These changes were originally introduced into master, but had to be reverted. For a full history of the changes and discussion see the below PR.
https://github.com/dxe/adb/pull/39
> feat(users): User Role Management

- main.go
- templates/header.html
- templates/logout.html
Adds logout functionality for users to logout of the currently signed in Google account.
We clear the server-side Auth Cookie, as well as log them out of the Google Sign In.
> faet(auth): User logout

- frontend/ActivistList.vue
- model/activist.go
- package-lock.json
Adds copying of activist details when doing an Activist Merge.
> feat(activists): Merge Activist Details

- frontend/EventEdit.vue
- main.go
- model/activist.go
- static/css/style.css
> Revert "Contact info indicators"

- main.go
- members/auth.go
> add SameSite=Strict attribute to cookies

- config/config.go
Fix typo in https://github.com/dxe/adb/pull/110
> Fix typo in https://github.com/dxe/adb/pull/110

- adb-forms/processor/processor.go
- automatically create output directories
> automatically create output directories

- adb-forms/processor/processor.go
- add directory creation error logging for debugging
> add directory creation error logging for debugging

- Dockerfile
- config/config.go
- add output folder to Docker container so the form processor can write to it
> add output folder to Docker container

- Dockerfile
- config/config.go
- main.go
- fix prod flag
- add output folder
> fix prod flag; add output folder

- Dockerfile
> fix dockerfile chown

- Dockerfile
> fix output folder creation

- Dockerfile
- change when the user is switched within Dockerfile
> change when the user is switched within Dockerfile

- .gitignore
- adb-forms/.gitignore
- clean up output folder now that it lives on the root
> clean up output folder

- Dockerfile
- add form_processor Dockerfile folder name fix
> add form_processor Dockerfile folder name fix

- form_processor/README.md
- form_processor/processor.go
- inline removeLockFile procedure
- clarify how to run tests in readme
> [From Processor] Inline removeLockFile procedure

- frontend/ActivistList.vue
- frontend/AdbNav.vue
- frontend/ChapterList.vue
- frontend/CirclesList.vue
- frontend/EventEdit.vue
- frontend/EventList.vue
- frontend/FormApply.vue
- frontend/FormDiscord.vue
- frontend/FormInterest.vue
- frontend/FormInternational.vue
- frontend/FormInternationalActions.vue
- frontend/UserList.vue
- frontend/WorkingGroupList.vue
- package-lock.json
- package.json
- pin version of `prettier` to `2.3.0` to make the CI and local development use the same version
- add the output of `make fmt`
> make the output of `make fmt` pass on master

- frontend/ActivistList.vue
- main.go
- model/db.go
- model/interactions.go
Basic interaction features. After these features are confirmed working in prod, we can continue extending functionality.
> Interactions

- package-lock.json
- package.json
Why: fix https://github.com/dxe/adb/issues/97
What: update `awesomplete` to include https://github.com/LeaVerou/awesomplete/commit/c9a8600aefd0bff80a3d40da574e1fbdb893b4e9
> [Issue #97] Update `awesomplete` to include tab behavior bugfix

- members/index.go
- members/roster.go
Matches the new rules adopted in dxe/dxesf-docs@ba03f738b2167d9a823f24ed9a827f874cff1884
> members: update Organizer voting eligibility

- members/index.go
> members: grant admin access to Antonelle

- members/members.go
- members/reminder.go
For now, just a listing of chapter members that need to sign the
voting agreement. Eventually, this will automate sending the email
too.
> members: add CM voting agreement reminder page

- form_processor/queries.go
- form_processor/testing_queries.go
- frontend/ActivistList.vue
- frontend/FormApply.vue
- model/activist.go
- model/db.go
- model/forms.go
Adds language & accessibility cols to application form, form processor, and activists table/view.
> Add language & accessibility cols

- frontend/ActivistList.vue
- model/activist.go
> show months since last event

- frontend/FormInternational.vue
- hooks/pre-commit
Update the wording of the question in the international application form, requested by Almira
> Update skills/interest question in intl app form

- frontend/ActivistList.vue
- frontend/package-lock.json
- frontend/package.json
fix running vue frontend in development
fix an issue that limited the columns SF Bay chapter users could view
> Fix issues from chapter switcher

- frontend/ActivistList.vue
- server/src/main.go
- server/src/model/activist.go
- shared/nav.json
New view that shows all activists that have done 3 actions or less in the last 6 months. Default range is 6 months from before the current date but user can change date range.
> New activists view 

- frontend/ActivistList.vue
https://app.asana.com/1/71341131816665/project/1209217418568645/task/1210941908798376
> fix: show city instead of fb column for non-sfbay activist list
